# Generated by Django 5.2.6 on 2025-09-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('emp', models.OneToOneField(db_column='emp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.email')),
            ],
        ),
    ]
