# Generated by Django 5.2.6 on 2025-09-25 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='emp',
            field=models.OneToOneField(db_column='email_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.email'),
        ),
    ]
