# Generated by Django 5.2.6 on 2025-09-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_salary_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='emp',
            new_name='email',
        ),
    ]
