# Generated by Django 5.2.6 on 2025-09-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_rename_emp_salary_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=4)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
