# Generated by Django 5.2.6 on 2025-09-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='exit', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
